### ISSUE TITLE
[BUG] The site is not loading anymore

### ISSUE THREAD

**Issue by TheFoxan12** [d-r-e/rncp#181]
The site is not loading anymore when we try to access it by login in with intra 42. It just redirects to the landing page.
The API seems to be sending a 401 UNAUTHORIZED error.
"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."

My hypothesis is that maybe the 42 api client_id and mostly the client_secret are not valid anymore and need to be changed.

**Comment by d-r-e** [comment]
Sorry, indeed, expired API secret. Thanks for the report, The app is back online.

**Comment by TheFoxan12** [comment]
Hey I think the secret is expired again

**Comment by d-r-e** [comment]
Thanks again, replaced the api key.

**Comment by tunsinge** [comment]
Hey, I think it is time again

**Comment by d-r-e** [comment]
You're a hero.
