### ISSUE TITLE
[Feature] Save API calls in a cache to save some API requests

### ISSUE THREAD

**Issue by louchebem06** [d-r-e/rncp#27]
Refresh 1 a day

**Comment by axelcoezard** [comment]
We should add that cache in the flask backend, using a file-cache to persist between server restarts.
The file cache should reset every night a 00:00 GMT+1 (intra time)

**Comment by axelcoezard** [comment]
With `Flask Caching` we can do that easly https://flask-caching.readthedocs.io/en/latest/
