### ISSUE TITLE
[Feature] Compute level

### ISSUE THREAD

**Issue by dams333** [d-r-e/rncp#78]
Hey,

First, thanks for the tool !

I have a suggestion: what do you think about update the `level` progress bar, depending on the selected projects (and add a way to select Internship projects and notes, like other projects) ? This could be very useful so that you don't have to do the math on the side and you have the complete computation for your RNCP

**Comment by axelcoezard** [comment]
Thank you for you suggestions !

1. I have just merged a PR that add the dynamic level calculation https://github.com/d-r-e/rncp/pull/90 (progess bar and level update) depending on selected projects.

2. For the Intership and Apprentissage projects, this is still in discussion. If you have any ideas of how to add them to the tool, we are open for suggestions! :raised_hands:
